import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { EdgeBlockedError, McpToolError } from '@chrischall/mcp-utils';
import { ThumbtackClient } from '../src/client.js';

function res(body: string, init: Partial<{ status: number; url: string; contentType: string }> = {}) {
  return new Response(body, {
    status: init.status ?? 200,
    headers: { 'content-type': init.contentType ?? 'text/html' },
  }) as Response & { url: string };
}
/** Response.url is read-only, so stamp it the way a redirect-followed fetch would. */
function withUrl(r: Response, url: string) {
  Object.defineProperty(r, 'url', { value: url });
  return r;
}

let fetchMock: ReturnType<typeof vi.fn>;
let client: ThumbtackClient;

beforeEach(() => {
  fetchMock = vi.fn();
  client = new ThumbtackClient({ fetchImpl: fetchMock as unknown as typeof fetch });
});
afterEach(() => vi.restoreAllMocks());

describe('getPage', () => {
  it('sends a browser User-Agent and follows redirects, reporting the final url', async () => {
    fetchMock.mockResolvedValue(withUrl(res('<html>ok</html>'), 'https://www.thumbtack.com/k/plumbers/near-me'));
    const page = await client.getPage('https://www.thumbtack.com/k/plumbing/near-me');
    expect(page.finalUrl).toBe('https://www.thumbtack.com/k/plumbers/near-me');
    expect(page.html).toContain('ok');
    const init = fetchMock.mock.calls[0][1];
    expect(init.redirect).toBe('follow');
    expect(String(init.headers['user-agent'])).toMatch(/Mozilla/);
  });

  it('raises an actionable error on a non-2xx', async () => {
    fetchMock.mockResolvedValue(withUrl(res('nope', { status: 503 }), 'https://x'));
    await expect(client.getPage('https://x')).rejects.toThrow(/503/);
  });

  // chrischall/mcp-host#1015: a CDN/WAF refusal page is not "the page moved".
  const CLOUDFRONT_403 =
    '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
    '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
    '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
    '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
    'Request blocked. We can\'t connect to the server for this app or website at this time.' +
    '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
    'Request ID: 3xAmPlE-Id==</PRE></BODY></HTML>';
  const CLOUDFLARE_403 =
    '<!DOCTYPE html><html lang="en-US"><head><title>Attention Required! | Cloudflare</title></head>' +
    '<body><div id="cf-wrapper"><div id="cf-error-details" class="cf-error-details-wrapper">' +
    '<h1>Sorry, you have been blocked</h1><h2>You are unable to access thumbtack.com</h2></div></div></body></html>';
  const CLOUDFLARE_CHALLENGE_403 =
    '<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title></head>' +
    '<body><noscript>Enable JavaScript and cookies to continue</noscript>' +
    '<script src="/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1"></script></body></html>';

  it.each([
    ['CloudFront', CLOUDFRONT_403],
    ['Cloudflare', CLOUDFLARE_403],
    ['Cloudflare', CLOUDFLARE_CHALLENGE_403],
  ])('reports a 403 %s refusal page as an edge block, not a moved page', async (vendor, body) => {
    fetchMock.mockResolvedValue(withUrl(res(body, { status: 403 }), 'https://x'));
    const err = await client.getPage('https://x').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect((err as EdgeBlockedError).vendor).toBe(vendor);
    expect((err as EdgeBlockedError).status).toBe(403);
    expect(String((err as Error).message)).not.toMatch(/moved/i);
  });

  it('reports a cf-mitigated response as an edge block whatever its body', async () => {
    fetchMock.mockResolvedValue(
      withUrl(new Response('denied', { status: 403, headers: { 'cf-mitigated': 'challenge' } }), 'https://x'),
    );
    await expect(client.getPage('https://x')).rejects.toBeInstanceOf(EdgeBlockedError);
  });

  it('control: a genuine 404 still reads as a moved page / unknown slug', async () => {
    fetchMock.mockResolvedValue(withUrl(res('<html><title>Page not found | Thumbtack</title></html>', { status: 404 }), 'https://x'));
    const err = await client.getPage('https://x').catch((e: unknown) => e);
    expect(err).not.toBeInstanceOf(EdgeBlockedError);
    expect(err).toBeInstanceOf(McpToolError);
    expect(String((err as McpToolError).message)).toMatch(/HTTP 404/);
    expect(JSON.stringify(err, Object.getOwnPropertyNames(err))).toMatch(/moved/i);
  });

  it('control: an origin 403 with no edge marker keeps its existing meaning', async () => {
    fetchMock.mockResolvedValue(withUrl(res('<html><title>403 Forbidden</title><body>Access Denied</body></html>', { status: 403 }), 'https://x'));
    const err = await client.getPage('https://x').catch((e: unknown) => e);
    expect(err).not.toBeInstanceOf(EdgeBlockedError);
    expect(String((err as McpToolError).message)).toMatch(/HTTP 403/);
  });

  it('control: a CloudFront page on a 503 is an origin outage, not a block', async () => {
    fetchMock.mockResolvedValue(withUrl(res(CLOUDFRONT_403.replace('403 ERROR', '503 ERROR'), { status: 503 }), 'https://x'));
    const err = await client.getPage('https://x').catch((e: unknown) => e);
    expect(err).not.toBeInstanceOf(EdgeBlockedError);
    expect(String((err as Error).message)).toMatch(/503/);
  });

  it('flags a Cloudflare interstitial as a bot wall rather than parsing it', async () => {
    fetchMock.mockResolvedValue(withUrl(res('<title>Just a moment...</title>'), 'https://x'));
    await expect(client.getPage('https://x')).rejects.toThrow(/bot|challenge|blocked/i);
  });

  it('surfaces a transport failure as unreachable', async () => {
    fetchMock.mockRejectedValue(new Error('ECONNREFUSED'));
    await expect(client.getPage('https://x')).rejects.toThrow(/thumbtack|unreachable|reach/i);
  });
});

describe('searchUrl', () => {
  it('builds the verified search path and encodes its inputs', async () => {
    fetchMock.mockResolvedValue(withUrl(res('<html/>'), 'https://final'));
    await client.searchPage('house cleaning', '28203');
    expect(fetchMock.mock.calls[0][0]).toBe(
      'https://www.thumbtack.com/k/house-cleaning/near-me?zip_code=28203',
    );
  });

  it('slugifies a free-text service name', async () => {
    fetchMock.mockResolvedValue(withUrl(res('<html/>'), 'https://final'));
    await client.searchPage('Lawn Mowing & Trimming', '90210');
    expect(fetchMock.mock.calls[0][0]).toContain('/k/lawn-mowing-trimming/');
  });
});

describe('graphql', () => {
  it('posts to the verified endpoint with an origin header', async () => {
    fetchMock.mockResolvedValue(withUrl(res(JSON.stringify({ data: { __typename: 'Query' } }), { contentType: 'application/json' }), 'https://app.thumbtack.com/graphql'));
    const out = await client.graphql('query{__typename}');
    expect(out).toEqual({ __typename: 'Query' });
    const [url, init] = fetchMock.mock.calls[0];
    expect(url).toBe('https://app.thumbtack.com/graphql');
    expect(init.method).toBe('POST');
    expect(init.headers.origin).toBe('https://www.thumbtack.com');
  });

  it('treats an errors[] body as a failure even though the status is 200', async () => {
    fetchMock.mockResolvedValue(withUrl(res(JSON.stringify({ errors: [{ message: 'badRequest' }], data: null }), { contentType: 'application/json' }), 'https://app.thumbtack.com/graphql'));
    await expect(client.graphql('query{x}')).rejects.toThrow(/badRequest/);
  });

  it('sends the browser User-Agent and JSON content-type on the GraphQL POST', async () => {
    fetchMock.mockResolvedValue(res(JSON.stringify({ data: { __typename: 'Query' } }), { contentType: 'application/json' }));
    await client.graphql('query{__typename}');
    const init = fetchMock.mock.calls[0][1];
    expect(String(init.headers['user-agent'])).toMatch(/Mozilla/);
    expect(init.headers['content-type']).toBe('application/json');
  });

  it('keeps the servicePage hint on an errors[] answer', async () => {
    fetchMock.mockResolvedValue(res(JSON.stringify({ errors: [{ message: 'badRequest' }] }), { contentType: 'application/json' }));
    const err = await client.graphql('query{x}').catch((e: unknown) => e);
    expect((err as { hint?: string }).hint).toMatch(/servicePage/);
  });

  it('reports a transport failure as a Thumbtack request failure', async () => {
    fetchMock.mockRejectedValue(new Error('ECONNRESET'));
    await expect(client.graphql('query{x}')).rejects.toThrow(/Thumbtack.*ECONNRESET/);
  });

  it('does not blindly JSON.parse a non-JSON body', async () => {
    fetchMock.mockResolvedValue(withUrl(res('<html>challenge</html>'), 'https://app.thumbtack.com/graphql'));
    await expect(client.graphql('query{x}')).rejects.toThrow(/json|html|unexpected/i);
  });
});

describe('cancellation (fleet-audit#767)', () => {
  it('getPage aborts its fetch when the tool call is cancelled, not only on timeout', async () => {
    const { withCallSignal } = await import('@chrischall/mcp-utils');
    const caller = new AbortController();
    let seen: AbortSignal | undefined;
    fetchMock.mockImplementation(async (_url: string, init: RequestInit) => {
      seen = init.signal ?? undefined;
      return withUrl(res('<html>ok</html>'), 'https://www.thumbtack.com/x');
    });
    await withCallSignal(caller.signal, () => client.getPage('https://www.thumbtack.com/x'));
    expect(seen).toBeDefined();
    expect(seen!.aborted).toBe(false);
    caller.abort(new Error('cancelled'));
    expect(seen!.aborted).toBe(true);
  });
});
